### ISSUE TITLE
Feature request - return index of currently set layer

### ISSUE THREAD

**Issue by tcb678** [zsa/kontroll#1]
One thing I've wished for a long time is an on-desktop indication of what layer I'm on.  Some quick status message from the Keymapp API would be very helpful here. Keymapp seems to know the active layer.  Can I request this feature?

**Comment by fdidron** [comment]
Hi @tcb678 

Sure that makes sense, something like `kontroll current-layer` that would return whatever the current layer is ?

**Comment by tcb678** [comment]
@fdidron That would be ideal.  Though for the maximalist, it would be good to just get a dump of the current state in a JSON object for easy parsing.  For instance, firmware version, layer, RGB animation mode, and any other interesting information that might be relevant.

**Comment by fdidron** [comment]
Got it, I like the idea of having the whole state, what I'm thinking of is :

```
$ kontroll status
Kontroll version: v1.x.x
Keymap version: v1.3.2
No keyboard connected OR
Keyboard: Voyager
Firmware version: default/latest
Current layer: 0
```
With an optional --json param to dump as json.

Then we can add more info as Keymapp, the firmware and kontroll evolve.
This will require a new version of Keymapp to be released, I'm going to plan this.

**Comment by fdidron** [comment]
This is pretty much coded, I need to release a new version of Keymapp to go along this. I have a release planned next week, I'll keep you posted.

![image](https://github.com/user-attachments/assets/74f675a5-fbf8-47d1-a77d-45874c59281a)

**Comment by fdidron** [comment]
This is released: https://github.com/zsa/kontroll/releases/tag/1.0.3

Make sure you update Keymapp to version 1.3.2.
