### ISSUE TITLE
App Store version of Keymapp not compatible with kontroll

### ISSUE THREAD

**Issue by mattorb** [zsa/kontroll#15]
Steps to repro issue
1. Downloaded Keymapp from App Store.
2. Downloaded kontroll from GitHub releases.
3. Started Keymapp, settings and turned on API
4. Attempt `kontroll list`
5. Receive error could not find socket: `/Users/blah/Library/Application Support/.keymapp/keymapp.sock`
6. do a recursive search for .keymapp, and spot it in `/Users/blah/Containers/io.zsa.keymapp/Data/Library/Application Support/.keymapp/keymapp.sock`.  'Containers'.  <-- socket being in a different location smells like App Store sandboxing 😄 
7. Note, the App Store version of Keymapp is several versions behind what the kontroll release notes say is compatible as well, so that at least got me searching.

Workaround, use the direct DL link:
1. Download Keymapp.app from direct download link (right under app store link) on https://www.zsa.io/flash
2. Start Keymapp.app and turn on API
3. `kontrol list` works now. 

Thanks for writing this CLI!

**Comment by fdidron** [comment]
@mattorb Thanks for the heads up, one way to make it work right now is to specify the port path when running commands:

**Comment by fdidron** [comment]
Fixed here https://github.com/zsa/kontroll/releases/tag/1.0.4
