### ISSUE TITLE
Getting the active layer

### ISSUE THREAD

**Issue by Makurisan** [zsa/kontroll#16]
It would be nice to have a command to get the active layer "get-layer". 
With this I could show in my app a green status otherwise red.

**Comment by fdidron** [comment]
Hi @Makurisan ,

This is already possible, if you run `kontroll status` you should get back
```
Keymapp version:        1.3.2
Kontroll version:       1.0.3
Connected keyboard:     Voyager
Firmware version:       xxx/xxx
Current layer:          0
```

It is also possible to get a json output from kontroll, `kontroll status --json`:

```JSON
{
  "keymapp_version": "1.3.2",
  "kontroll_version": "1.0.3",
  "keyboard": {
    "friendly_name": "Voyager",
    "firmware_version": "xxx/xxx",
    "current_layer": 0
  }
}
```
