### ISSUE TITLE
Convert and publish as a crate lib

### ISSUE THREAD

**Issue by gak** [zsa/kontroll#3]
I totally realise this is just a demo for usage, but it would be handy to also treat this code as a library so that users can use it.

If this is something ZSA doesn't have the resources to pursue at the moment, I'd be happy to fork the code and maintain a library version myself.

(BTW Thank you for creating this project!)

**Comment by fdidron** [comment]
That's a very good idea and I already started work on this because I needed to be  able to access the API inside integration tests.

I think the lib will expose a struct including each api methods.

**Comment by fdidron** [comment]
Kontroll is available as a crate here:
https://crates.io/crates/kontroll
https://docs.rs/kontroll/latest/kontroll/
